create extension if not exists "pgcrypto";
create extension if not exists "pg_cron";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  preferred_language text not null default 'en' check (preferred_language in ('en', 'hi')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.candles (
  id bigint generated by default as identity primary key,
  symbol text not null default 'XAU/USD',
  timeframe text not null default '1m' check (timeframe in ('1m', '5m', '15m', '30m', '1h')),
  open double precision not null,
  high double precision not null,
  low double precision not null,
  close double precision not null,
  volume double precision not null default 0,
  timestamp timestamptz not null,
  created_at timestamptz not null default now(),
  unique (symbol, timeframe, timestamp)
);

create table if not exists public.bots (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  description text not null default '',
  code_content text not null default '',
  language text not null check (language in ('python', 'json_strategy')),
  version text not null default '1.0',
  is_active boolean not null default false,
  parameters jsonb not null default '{}'::jsonb,
  magic_number integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, magic_number)
);

create table if not exists public.paper_accounts (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance double precision not null default 10000,
  equity double precision not null default 10000,
  initial_balance double precision not null default 10000,
  currency text not null default 'USD',
  max_daily_loss double precision not null default 500,
  max_lot_size double precision not null default 1.0,
  updated_at timestamptz not null default now()
);

create table if not exists public.paper_trades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  bot_id uuid references public.bots(id) on delete set null,
  symbol text not null default 'XAU/USD',
  side text not null check (side in ('BUY', 'SELL')),
  entry_price double precision not null,
  exit_price double precision,
  sl double precision,
  tp double precision,
  lot_size double precision not null,
  pnl double precision not null default 0,
  commission double precision not null default 0,
  status text not null check (status in ('OPEN', 'CLOSED', 'CANCELLED')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  magic_number integer not null,
  comment text
);

create table if not exists public.bot_logs (
  id bigint generated by default as identity primary key,
  bot_id uuid references public.bots(id) on delete cascade,
  level text not null check (level in ('INFO', 'WARN', 'ERROR', 'SIGNAL')),
  message text not null,
  candle_timestamp timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.user_settings (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  risk_percent double precision not null default 1.0,
  max_open_trades integer not null default 3,
  enable_news_filter boolean not null default false,
  trading_sessions jsonb not null default '{"london": true, "newyork": true, "asian": false}'::jsonb,
  notification_prefs jsonb not null default '{}'::jsonb
);

create index if not exists idx_candles_symbol_time on public.candles(symbol, timeframe, timestamp desc);
create index if not exists idx_trades_user_status on public.paper_trades(user_id, status);
create index if not exists idx_bots_active on public.bots(is_active) where is_active = true;
create unique index if not exists idx_bots_user_magic on public.bots(user_id, magic_number);

alter table public.profiles enable row level security;
alter table public.candles enable row level security;
alter table public.bots enable row level security;
alter table public.paper_accounts enable row level security;
alter table public.paper_trades enable row level security;
alter table public.bot_logs enable row level security;
alter table public.user_settings enable row level security;

drop policy if exists "profiles are own rows" on public.profiles;
create policy "profiles are own rows" on public.profiles for all using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists "candles are public read" on public.candles;
create policy "candles are public read" on public.candles for select using (true);
drop policy if exists "bots are own rows" on public.bots;
create policy "bots are own rows" on public.bots for all using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "accounts are own rows" on public.paper_accounts;
create policy "accounts are own rows" on public.paper_accounts for all using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "trades are own rows" on public.paper_trades;
create policy "trades are own rows" on public.paper_trades for all using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "logs are own rows" on public.bot_logs;
create policy "logs are own rows" on public.bot_logs for select using (
  exists (select 1 from public.bots b where b.id = bot_id and b.user_id = auth.uid())
);
drop policy if exists "settings are own rows" on public.user_settings;
create policy "settings are own rows" on public.user_settings for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email);
  insert into public.paper_accounts (user_id) values (new.id);
  insert into public.user_settings (user_id) values (new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.delete_old_candles()
returns void language sql security definer set search_path = public as $$
  delete from public.candles where timeframe = '1m' and timestamp < now() - interval '30 days';
$$;

select cron.schedule('goldscalper-retention', '15 0 * * *', $$select public.delete_old_candles()$$)
where not exists (select 1 from cron.job where jobname = 'goldscalper-retention');

do $$ begin
  alter publication supabase_realtime add table public.candles;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.paper_trades;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.paper_accounts;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.bots;
exception when duplicate_object then null;
end $$;